nodeLinker: node-modules
npmScopes:
  big-whale-labs:
    npmAlwaysAuth: true
    npmAuthToken: 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

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: 'https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
